### ISSUE TITLE
ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred while collecting items to be installed

### ISSUE THREAD

**Issue by edityomurti** [vorburger/opendaylight-eclipse-setup#6]
Hi @vorburger ,
I was following your great tutorial from here : https://www.youtube.com/watch?v=BLW8aOh6WeQ ,
with the Eclipse Oxygen then I encountered this error. I already tried several times but comes up with the same error. Can you help me?

```
Collected 3 artifacts for http://download.eclipse.org/releases/oxygen/201804111000 in 12.274s
An error was detected while performing the engine operation and the changes are being rolled back. See the log for details.
ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred while collecting items to be installed
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:547)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:340)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:729)

**Comment by vorburger** [comment]
> with the Eclipse Oxygen then I encountered this error

could you try with Photon (latest Milestone, even if not yet released; doesn't matter) instead of Oxygen, and see if that helps?

> See the log for details.

can you copy/paste more of the log in the Wizard UI - what you have provided above just says that it failed, but I can't tell why - that should appear a little earlier if you scroll up.

**Comment by edityomurti** [comment]
> try with Photon

**Comment by edityomurti** [comment]
@vorburger Thanks for replying.
> try with Photon

I tried with Photon but comes up with the same error :
```
Collected 3 artifacts for http://download.eclipse.org/releases/photon in 6.29s
Collecting 1 artifacts from http://findbugs.cs.umd.edu/eclipse-daily/
Downloading edu.umd.cs.findbugs.plugin.eclipse
Mirrored 1 artifacts from http://findbugs.cs.umd.edu/eclipse-daily/ at 0kb/s with 1 failures
Collected 1 artifacts for http://findbugs.cs.umd.edu/eclipse-daily/ in 0.564s
An error was detected while performing the engine operation and the changes are being rolled back. See the log for details.
ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred while collecting items to be installed
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:547)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:340)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:729)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3324)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3252)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3233)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3133)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
  ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=_Users_edityomurti_lispflowmapping-master5_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
  ERROR: org.eclipse.equinox.p2.transport.ecf code=1200 Artifact not found: http://findbugs.cs.umd.edu/eclipse-daily/plugins/edu.umd.cs.findbugs.plugin.eclipse_3.0.2.20170921-25417ff.jar.
  java.io.FileNotFoundException: http://findbugs.cs.umd.edu/eclipse-daily/plugins/edu.umd.cs.findbugs.plugin.eclipse_3.0.2.20170921-25417ff.jar
    at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryStatusHelper.checkFileNotFound(RepositoryStatusHelper.java:297)
```
> copy/paste more of the log in the Wizard UI

Actually I couldn't find the log in the Wizard UI, where do I should take a look?

<img width="892" alt="error_odl_eclipse" src="https://user-images.githubusercontent.com/14180222/39659356-d2cebdf2-5050-11e8-8553-1f9921ffbc1e.png">

**Comment by vorburger** [comment]
> I tried with Photon but comes up with the same error :

It's not the same error, we can now see that there is some problem with the p2 site for the FindBugs Eclipse plug-in... http://findbugs.cs.umd.edu/eclipse-daily/ works, but http://findbugs.cs.umd.edu/eclipse-daily/plugins/edu.umd.cs.findbugs.plugin.eclipse_3.0.2.20170921-25417ff.jar is broken, for some reason.

I'll try to reproduce this ASAP and see if perhaps changing the URL to not use the `-daily` this gets fixed.

@edityomurti what you show in the screenshot above is what I meant by "Wizard UI", but you have

**Comment by vorburger** [comment]
@edityomurti I've spent a moment trying to reproduce this problem, but cannot!

If a I try a fresh install, checking e.g. lispflowmapping, and to make sure that I don't have anything cached from a previous installation create a completely separate new Bundle Pool, it works for me... see https://gist.github.com/vorburger/c0a641b9b464e3163946756046c0dbc7, note:

    Installing edu.umd.cs.findbugs.plugin.eclipse [3.0.2.20170921-25417ff]

I'm not quite sure yet how this can work for me, but not for you. Which exact version of the Eclipse Installer (Oomph) are you using? At the bottom, before the <Back button, what does it say? I have a 1.9.0 Build 3502... if the little spining wheel arrows right on the left of the version are animated, then try to click on that to update the the Eclipse Installer, and see if that helps. Also try creating a new Bundle Pool (or just completely delete your existing one; careful this will break any other previous Eclipse' you have installed), to see if that helps.

**Comment by vorburger** [comment]
https://lists.opendaylight.org/pipermail/dev/2018-May/005040.html has another user hitting this.

So, despite not being able to reproduce it, I think it it perhaps time for and best not to let the overall opendaylight-eclipse-setup be blocked / held back by these inexplicable sporadic FindBugs Eclipse plugin installation issues... I'll therefore move FindBugs into the "Additional optional Eclipse plugins" section instead of mandatorily always install it as a must have. @edityomurti this will solve the problem for you as well.

PS: We want to eventually completely move away from FindBugs to SpotBugs anyway (as well as adopt Error Prone from infrautils:parent more...). That reminds me - due to https://github.com/m2e-code-quality/m2e-code-quality/pull/113, I need to find time to fork m2e-code-quality which seems unmaintained now (https://github.com/m2e-code-quality/m2e-code-quality/pull/116 and https://github.com/m2e-code-quality/m2e-code-quality/pull/115).

**Comment by vorburger** [comment]
Above meanwhile happened, so FindBugs completely removed in 39500735854d06b9926be17805fdbc1c9a1cc204.
