### ISSUE TITLE
install stops with error because http://ifedorenko.github.com/m2e-extras/. not provided binary anymore

### ISSUE THREAD

**Issue by HighstreetHerbert** [vorburger/opendaylight-eclipse-setup#9]
See: https://github.com/ifedorenko/com.ifedorenko.m2e.mavendev/issues/14
Related to Install 404 error: "ERROR: org.eclipse.equinox.p2.metadata.repository code=1000 No repository found at http://ifedorenko.github.com/m2e-extras/."

**Comment by vorburger** [comment]
@HighstreetHerbert thanks for your interest. FYI I don't actively maintain this anymore. Would you have any interest in helping with maintaining this? The solution here is simply to remove all uses of `ifedorenko` from [the org.opendaylight.projects.setup file](https://github.com/vorburger/opendaylight-eclipse-setup/blob/master/org.opendaylight.projects.setup).. would you perhaps like to raise a PR for this?

**Comment by vorburger** [comment]
> raise a PR for this?

actually I just did it

**Comment by HighstreetHerbert** [comment]
Thanks a lot.
